language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
cache: pip
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - pip install tox-travis coveralls
script:
  - tox
after_success:
  - coverage combine .coverage && coveralls
