language: python
python: 3.6
cache: pip
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - pip install tox-travis coveralls
  - tox -e py27 -e py36 -e flake8
after_success:
  - coverage combine .coverage && coveralls
